### ISSUE TITLE
tests: prepare local development test cluster

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#13]
In order to have a local working cluster the following things need to be done:
- [x] Make current configuration in https://github.com/reanahub/reana-resources-k8s abstract, so local/production configuration can be automatically generated on demand. (https://github.com/reanahub/reana-resources-k8s/issues/17)
- [x] Deploy current system using [minikube](https://github.com/kubernetes/minikube/releases).
- [x] ~~Create a CephFS cluster.~~ Use host directories to mock distributed file system.
- [x] Add documentation to deploy and test locally. (https://github.com/reanahub/reana/issues/4)
- [x] Create `hello world` example. (https://github.com/reanahub/reana-demo-helloworld/issues/2)

**Comment by tiborsimko** [comment]
Perhaps [Vagrant sync folders](https://www.vagrantup.com/docs/synced-folders/basic_usage.html) can be used? I had a good experience with shared folders in a multi-VM environment for light cache sharing (some R/W, but mostly R/O accesses by VMs). I did not test any heavy R/W race conditions at the time though...

**Comment by lukasheinrich** [comment]
perhaps for super local environment, just a mounted host directory could be used?

**Comment by diegodelemos** [comment]
If we suppose that the local environment is always going to be run in only one VM we could. This is true for the current minikube version, which creates the full cluster in one VM, but we do not know what will happen in the near future or even if we will want more than one VM for some reason.

Shall we stay simple for now and try host directories and let see what happens later?

**Comment by tiborsimko** [comment]
> Shall we stay simple for now and try host directories and let see what happens later?

Sounds good! 👍

**Comment by tiborsimko** [comment]
The local development environment is now available. The docs have been added. Closing the issue.

**Comment by anton-khodak** [comment]
@tiborsimko can you please point to the appropriate docs?
