### ISSUE TITLE
Merge `maint-0.7` to `master`

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana#480]
Recipe:

```console
$ reana-dev git-upgrade -c ALL
$ reana-dev git-checkout -c ALL master
$ cd reana-ui
$ reana-dev git-upgrade -c . --base maint-0.7
$ reana-dev git-upgrade -c .
$ git checkout -b merge
$ git log master..maint-0.7  # what changes we would merge?
$ git merge --log maint-0.7  
$ git status # file1.py and file2.py have conflicts
$ vim file1.py # solve conflicts
$ git add file1.py
$ vim file2.py # solve more conflicts
$ git add file2.py
$ git status # all clean
$ git merge --continue # we are done!
$ git diff master merge # inspect all code changes
$ reana-dev run-ci ... # try to run; whoops, it's broken
$ vim file3.py # some other file may needs adaptation
$ git add file3.py
$ git commit --amend
$ git show master:file4.py > file4.py # some yet another file may be easier to edit out again from its master state
$ vim file4.py
$ git add file4.py
$ git commit --amend
$ git diff master merge # one last look
$ reana-dev run-ci ... # let's retest 
```

- [x] [reana-ui](https://github.com/reanahub/reana-ui/pull/176)
- [x] ~pytest-reana~ (no changes)
- [x] [reana-commons](https://github.com/reanahub/reana-commons/pull/247)
- [x] [reana-db](https://github.com/reanahub/reana-db/pull/120)
- [x] [reana-client](https://github.com/reanahub/reana-client/pull/456)
- [x] [reana-job-controller](https://github.com/reanahub/reana-job-controller/pull/296)
- [x] [reana-message-broker](https://github.com/reanahub/reana-message-broker/pull/35)
- [x] [reana-server](https://github.com/reanahub/reana-server/pull/338)
- [x] [reana-workflow-controller](https://github.com/reanahub/reana-workflow-controller/pull/361)
- [x] [r-w-e-cwl](https://github.com/reanahub/reana-workflow-engine-cwl/pull/166)
- [x] [r-w-e-serial](https://github.com/reanahub/reana-workflow-engine-serial/pull/131)
- [x] [r-w-e-yadage](https://github.com/reanahub/reana-workflow-engine-yadage/pull/177)
- [x] [reana](https://github.com/reanahub/reana/pull/481)

##### TODO:

- Test user email confirmation features
- Test hiding sign up form

**Comment by tiborsimko** [comment]
The PR set works well :+1:  Going to proceed to checking and merging PRs one by one.

WRT A vs B, this will apply also to `maint-0.7` branch, so we can solve the issue there.  Currently, we simply warn admins via docs that they should set up sender information, but also SMTP information, for the email notification service to work.  I guess we could make a nicer check on the application level, e.g. you can get into a situation where SMTP credential is outdated... So runtime treatment to make these "continuable error" situations would be preferable.  We can create a new issue on this for `maint-0.7`.
