### ISSUE TITLE
sprint: Basic-Tests kick-off

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana#89]
# Basic tests sprint kick-off

### Dates

GanttStart: 2018-10-01
GanttDue: 2018-10-12

### People

- @diegodelemos (10d) 
- @dinosk (10d) 
- @tiborsimko (10d)

### Goals

- Implement the minimum test infrastructure for all REANA components, involving mostly mocking of:
    - AMQP
    - Celery
    - REST API (OpenAPI specs)
    - Filesystem
- Extract the test fixtures to a common repository to share across components.

### Kanban

- kanban board https://waffle.io/reanahub/reana?milestone=Basic-Tests

### Tasks

- Basic testing infrastructure:
  - [x] (https://github.com/reanahub/reana-pytest-commons/issues/1) Bootstrap new repo containing `pytest` fixtures
  - [x] (https://github.com/reanahub/reana/issues/91) REST mock
  - [x] (https://github.com/reanahub/reana-workflow-controller/issues/131, https://github.com/reanahub/reana-commons/issues/46) AMQP mock
  - [x] (https://github.com/reanahub/reana-workflow-controller/issues/132) Code including Celery tasks calls (currently we are "hacking" it, see [here](https://github.com/reanahub/reana-workflow-controller/blob/master/reana_workflow_controller/rest.py#L1301))
  - [x] (https://github.com/reanahub/reana-pytest-commons/issues/4) Try [FS fixture](https://github.com/reanahub/reana-workflow-controller/blob/master/tests/conftest.py#L40) on a different component (i.e. REANA-Server) so when we extract it it will work.
  - [x] (https://github.com/reanahub/reana-pytest-commons/issues/3) Try [DB fixture](https://github.com/reanahub/reana-workflow-controller/blob/master/tests/conftest.py#L68) on a different component (i.e. REANA-Job-Controller) so when we extract, it will work.
  - [ ] **POSTPONED** until Rich-Tests sprint. (https://github.com/reanahub/reana/issues/90) Get a Kubernetes cluster running on CI environment with service account token ([needed by REANA-Job-Controller](https://github.com/reanahub/reana-cluster/blob/master/reana_cluster/backends/kubernetes/templates/deployments/job-controller-template.yaml#L60-L62)) and test that examples work using [`reana` CLI](https://reana.readthedocs.io/en/latest/developerguide.html#reana) (`reana install-client`, `reana install-cluster`, `reana run-example`...).

**Comment by diegodelemos** [comment]
Closing sprint, everything has been accomplished but the CI setup.

> **POSTPONED** until Rich-Tests sprint. (https://github.com/reanahub/reana/issues/90) Get a Kubernetes cluster running on CI environment with service account token ([needed by REANA-Job-Controller](https://github.com/reanahub/reana-cluster/blob/master/reana_cluster/backends/kubernetes/templates/deployments/job-controller-template.yaml#L60-L62)) and test that examples work using [`reana` CLI](https://reana.readthedocs.io/en/latest/developerguide.html#reana) (`reana install-client`, `reana install-cluster`, `reana run-example`...).
